config/routes.rb
Rails.application.routes.draw do
  get 'accounts/search' =>  'accounts#search'
  resources :accounts
  
  get 'about' => 'pages#about'

  root 'pages#home' 

end

app/models/account.rb
class Account
  include Mongoid::Document
  field :name, type: String
  field :account_number, type: String
  field :fake_ssn, type: String
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  def search
    @accounts = Account.all.shuffle[0..4]
  end
  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :account_number, :fake_ssn)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :account_number
    = f.text_field :account_number
  .field
    = f.label :fake_ssn
    = f.text_field :fake_ssn
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
.row
  .medium-12.large12.columns
    %h1 Accounts
  .medium-4.large-3.columns
    = render 'shared/account_search'
  .medium-8.large-9.columns
    %table
      %thead
        %tr
          %th Name
          %th Account number
          %th Fake ssn

      %tbody
        - @accounts.each do |account|
          %tr
            %td= account.name
            %td= account.account_number
            %td= account.fake_ssn

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @account.name
%p
  %b Account number:
  = @account.account_number
%p
  %b Fake ssn:
  = @account.fake_ssn

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'shared/im_too_lazy_styling' %>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.haml
.row.about
  .medium-6.large-4.columns
    = render 'shared/account_search'
  .medium-6.large-8.columns
    %h4 Imagine this is really important text
    %p Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.

app/views/shared/_account_search.html.haml
%p react powered search box

= react_component('AccountSearch', {name: 'fake name', accountNumber: '12345678'    , fakeSsn: 'XXX-XX-1234' })

app/views/shared/_footer.html.haml
%footer.row
  .large-12.columns
    .row
      .large-6.columns
        %p © Copyright no one at all. Go to town.

app/views/shared/_header.html.haml
.row
  .small-12.medium-4.large-6.columns.namelogo
    %h1= link_to 'React+Rails Demo', root_path
  .small-12.medium-8.large-6.columns
    .nav-bar
      %ul.button-group
        %li
          = link_to "My Book", accounts_path, class: 'button'